modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "iteminteractions"
version = "${version}"
displayName = "iteminteractions"
authors = "mineland"
description = '''
Item interactions in your inventory!
'''
logoFile = "iteminteractions-icon.png"

[[dependencies.iteminteractions]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iteminteractions]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.iteminteractions]]
#modId = "architectury"
#type = "required"
#versionRange = "[16.0.3,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "iteminteractions.mixins.json"

